version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}?schema=public
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install && npx prisma generate && npx prisma migrate dev && npm run seed && npm run start:dev"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
